// services.ts — NEXTAN Costing & Quote Generator
// Generated by Gemini (models/gemini-2.5-flash) via chunked streaming, assembled by Cowork
//
// AUTOSAVE PATTERN: useMutation without invalidateQueries.
// Cache updated via queryClient.setQueryData() after success — prevents write-read loops.
// See ADR-001 for JWT storage decision.
import apiClient from './axios';

export type LineItem = {
  id: string;
  scenario_id: string;
  parent_line_item_id?: string | null;
  section: string;
  display_order: number;
  description: string;
  sub_specs?: string | null;
  qty: string;
  unit: string;
  cost_rate: string;
  cost_currency: string;
  markup_pct: string;
  cost_rate_sgd?: string | null;
  bundle_override_price?: string | null;
  is_bundle?: boolean;
  created_at: string;
  updated_at: string;
};


// ── Auth & Users ───────────────────────────────────────────

/**
 * @purpose Authenticates a user with provided credentials.
 * @param credentials { username: string; password: string; } - The user's login credentials.
 * @returns { Promise<{ access_token: string; refresh_token: string; token_type?: string; }> } A promise that resolves to an object containing authentication tokens.
 * @owner Gemini
 */
export async function loginUser(credentials: {
  username: string;
  password: string;
}): Promise<{
  access_token: string;
  refresh_token: string;
  token_type?: string;
}> {
  const response = await apiClient.post<{
    access_token: string;
    refresh_token: string;
    token_type?: string;
  }>(`/api/v1/auth/login`, credentials);
  return response.data;
}

/**
 * @purpose Refreshes the authentication access token using a valid refresh token.
 * @param refreshToken { refresh_token: string; } - The refresh token object.
 * @returns { Promise<{ access_token: string; token_type?: string; }> } A promise that resolves to an object containing a new access token.
 * @owner Gemini
 */
export async function refreshAuthToken(refreshToken: {
  refresh_token: string;
}): Promise<{
  access_token: string;
  token_type?: string;
}> {
  const response = await apiClient.post<
    { refresh_token: string },
    { access_token: string; token_type?: string }
  >(`/api/v1/auth/refresh`, refreshToken);
  return response;
}

/**
 * @purpose Retrieves information about the currently authenticated user.
 * @param _ No parameters are required.
 * @returns { Promise<{ id: string; numeric_user_id: number; username: string; created_at: string; }> } A promise that resolves to the current user's details.
 * @owner Gemini
 */
export async function getMe(): Promise<{
  id: string;
  numeric_user_id: number;
  username: string;
  created_at: string;
}> {
  const response = await apiClient.get<
    { id: string; numeric_user_id: number; username: string; created_at: string }
  >(`/api/v1/users/me`);
  return response.data;
}
// ── Organisations & Contacts ───────────────────────────────────────────


/**
 * @purpose Lists organisations with optional query parameters for filtering.
 * @param {object} [params] - Optional query parameters.
 * @param {string} [params.q] - Search query for organisations.
 * @returns {Promise<Array<{id: string, name: string, address?: any, created_by_user_id: string, created_at: string, updated_at: string}>>} A promise that resolves to an array of organisation objects.
 * @owner Gemini
 */
export async function listOrganisations(params?: { q?: string }): Promise<Array<{ id: string; name: string; address?: any; created_by_user_id: string; created_at: string; updated_at: string }>> {
  const response = await apiClient.get<Array<{ id: string; name: string; address?: any; created_by_user_id: string; created_at: string; updated_at: string }>>(`/api/v1/organisations`, { params });
  return response.data;
}

/**
 * @purpose Creates a new organisation.
 * @param {object} data - The data for the new organisation.
 * @param {string} data.name - The name of the organisation.
 * @param {any} [data.address] - The address of the organisation.
 * @returns {Promise<void>} A promise that resolves when the organisation is created.
 * @owner Gemini
 */
export async function createOrganisation(data: { name: string; address?: any }): Promise<void> {
  await apiClient.post<void>(`/api/v1/organisations`, data);
}

/**
 * @purpose Autocompletes organisation names based on a query.
 * @param {string} query - The search query for organisation names.
 * @returns {Promise<Array<{id: string, name: string}>>} A promise that resolves to an array of simplified organisation objects.
 * @owner Gemini
 */
export async function autocompleteOrganisations(query: string): Promise<Array<{ id: string; name: string }>> {
  const response = await apiClient.get<Array<{ id: string; name: string }>>(`/api/v1/organisations/autocomplete`, { params: { q: query } });
  return response.data;
}

/**
 * @purpose Retrieves a single organisation by its ID.
 * @param {string} orgId - The unique identifier of the organisation.
 * @returns {Promise<{id: string, name: string, address?: any, created_by_user_id: string, created_at: string, updated_at: string}>} A promise that resolves to the organisation object.
 * @owner Gemini
 */
export async function getOrganisation(orgId: string): Promise<{ id: string; name: string; address?: any; created_by_user_id: string; created_at: string; updated_at: string }> {
  const response = await apiClient.get<{ id: string; name: string; address?: any; created_by_user_id: string; created_at: string; updated_at: string }>(`/api/v1/organisations/${orgId}`);
  return response.data;
}

/**
 * @purpose Updates an existing organisation.
 * @param {string} orgId - The unique identifier of the organisation to update.
 * @param {object} data - The update data for the organisation.
 * @param {any} [data.name] - The new name for the organisation.
 * @param {any} [data.address] - The new address for the organisation.
 * @returns {Promise<{id: string, name: string, address?: any, created_by_user_id: string, created_at: string, updated_at: string}>} A promise that resolves to the updated organisation object.
 * @owner Gemini
 */
export async function updateOrganisation(orgId: string, data: { name?: any; address?: any }): Promise<{ id: string; name: string; address?: any; created_by_user_id: string; created_at: string; updated_at: string }> {
  const response = await apiClient.put<{ id: string; name: string; address?: any; created_by_user_id: string; created_at: string; updated_at: string }>(`/api/v1/organisations/${orgId}`, data);
  return response.data;
}

/**
 * @purpose Deletes an organisation by its ID.
 * @param {string} orgId - The unique identifier of the organisation to delete.
 * @returns {Promise<void>} A promise that resolves when the organisation is deleted.
 * @owner Gemini
 */
export async function deleteOrganisation(orgId: string): Promise<void> {
  await apiClient.delete<void>(`/api/v1/organisations/${orgId}`);
}

/**
 * @purpose Lists contacts associated with a specific organisation.
 * @param {string} orgId - The unique identifier of the organisation.
 * @returns {Promise<Array<{id: string, organisation_id: string, name: string, email?: any, phone?: any, created_by_user_id: string, created_at: string, updated_at: string}>>} A promise that resolves to an array of contact objects.
 * @owner Gemini
 */
export async function listOrgContacts(orgId: string): Promise<Array<{ id: string; organisation_id: string; name: string; email?: any; phone?: any; created_by_user_id: string; created_at: string; updated_at: string }>> {
  const response = await apiClient.get<Array<{ id: string; organisation_id: string; name: string; email?: any; phone?: any; created_by_user_id: string; created_at: string; updated_at: string }>>(`/api/v1/organisations/${orgId}/contacts`);
  return response.data;
}

/**
 * @purpose Creates a new contact for a specific organisation.
 * @param {string} orgId - The unique identifier of the organisation.
 * @param {object} data - The data for the new contact.
 * @param {string} data.name - The name of the contact.
 * @param {any} [data.email] - The email of the contact.
 * @param {any} [data.phone] - The phone number of the contact.
 * @returns {Promise<void>} A promise that resolves when the contact is created.
 * @owner Gemini
 */
export async function createOrgContact(orgId: string, data: { name: string; email?: any; phone?: any }): Promise<void> {
  await apiClient.post<void>(`/api/v1/organisations/${orgId}/contacts`, data);
}

/**
 * @purpose Autocompletes contact names for a specific organisation based on a query.
 * @param {string} orgId - The unique identifier of the organisation.
 * @param {string} query - The search query for contact names.
 * @returns {Promise<Array<{id: string, name: string, email?: any}>>} A promise that resolves to an array of simplified contact objects.
 * @owner Gemini
 */
export async function autocompleteOrgContacts(orgId: string, query: string): Promise<Array<{ id: string; name: string; email?: any }>> {
  const response = await apiClient.get<Array<{ id: string; name: string; email?: any }>>(`/api/v1/organisations/${orgId}/contacts/autocomplete`, { params: { q: query } });
  return response.data;
}

/**
 * @purpose Retrieves a single contact by its ID.
 * @param {string} contactId - The unique identifier of the contact.
 * @returns {Promise<{id: string, organisation_id: string, name: string, email?: any, phone?: any, created_by_user_id: string, created_at: string, updated_at: string}>} A promise that resolves to the contact object.
 * @owner Gemini
 */
export async function getContact(contactId: string): Promise<{ id: string; organisation_id: string; name: string; email?: any; phone?: any; created_by_user_id: string; created_at: string; updated_at: string }> {
  const response = await apiClient.get<{ id: string; organisation_id: string; name: string; email?: any; phone?: any; created_by_user_id: string; created_at: string; updated_at: string }>(`/api/v1/contacts/${contactId}`);
  return response.data;
}

/**
 * @purpose Updates an existing contact.
 * @param {string} contactId - The unique identifier of the contact to update.
 * @param {object} data - The update data for the contact.
 * @param {any} [data.name] - The new name for the contact.
 * @param {any} [data.email] - The new email for the contact.
 * @param {any} [data.phone] - The new phone number for the contact.
 * @returns {Promise<{id: string, organisation_id: string, name: string, email?: any, phone?: any, created_by_user_id: string, created_at: string, updated_at: string}>} A promise that resolves to the updated contact object.
 * @owner Gemini
 */
export async function updateContact(contactId: string, data: { name?: any; email?: any; phone?: any }): Promise<{ id: string; organisation_id: string; name: string; email?: any; phone?: any; created_by_user_id: string; created_at: string; updated_at: string }> {
  const response = await apiClient.put<{ id: string; organisation_id: string; name: string; email?: any; phone?: any; created_by_user_id: string; created_at: string; updated_at: string }>(`/api/v1/contacts/${contactId}`, data);
  return response.data;
}

/**
 * @purpose Deletes a contact by its ID.
 * @param {string} contactId - The unique identifier of the contact to delete.
 * @returns {Promise<void>} A promise that resolves when the contact is deleted.
 * @owner Gemini
 */
export async function deleteContact(contactId: string): Promise<void> {
  await apiClient.delete<void>(`/api/v1/contacts/${contactId}`);
}

// ── Costing Sheets ───────────────────────────────────────────

/**
 * @purpose Creates a new costing sheet.
 * @param data The data for creating the costing sheet.
 * @returns A Promise that resolves to the newly created costing sheet.
 * @owner Gemini
 */
export async function createCostingSheet(data: {
  quote_title: string;
  date?: string;
  client_name: string;
  organisation_id?: string;
  contact_id?: string;
  contact_name?: string;
  contact_email?: string;
  payment_term?: string;
  quotation_validity_days?: number;
  lead_time?: string;
  local_tax?: string;
  warranty?: string;
  notes_and_exclusions?: string;
  terms_and_conditions?: string;
  [key: string]: any; // For any other unspecified optional fields
}): Promise<{
  id: string;
  user_id: string;
  ref_number: string;
  date: string;
  quote_title: string;
  organisation_id?: string;
  client_name: string;
  contact_id?: string;
  contact_name?: string;
  contact_email?: string;
  payment_term?: string;
  quotation_validity_days: number;
  lead_time?: string;
  local_tax?: string;
  warranty?: string;
  notes_and_exclusions?: string;
  terms_and_conditions?: string;
  created_at: string;
  updated_at: string;
  [key: string]: any; // For any other unspecified fields
}> {
  const response = await apiClient.post<
    {
      id: string;
      user_id: string;
      ref_number: string;
      date: string;
      quote_title: string;
      organisation_id?: string;
      client_name: string;
      contact_id?: string;
      contact_name?: string;
      contact_email?: string;
      payment_term?: string;
      quotation_validity_days: number;
      lead_time?: string;
      local_tax?: string;
      warranty?: string;
      notes_and_exclusions?: string;
      terms_and_conditions?: string;
      created_at: string;
      updated_at: string;
      [key: string]: any;
    }
  >(`/api/v1/costing-sheets`, data);
  return response.data;
}

/**
 * @purpose Lists all costing sheets, with optional filtering.
 * @param params Optional query parameters for filtering (client_name, ref_number, date_from, date_to).
 * @returns A Promise that resolves to an array of costing sheets.
 * @owner Gemini
 */
export async function listCostingSheets(params?: {
  client_name?: string;
  ref_number?: string;
  date_from?: string;
  date_to?: string;
}): Promise<
  {
    id: string;
    ref_number: string;
    quote_title: string;
    date: string;
    client_name: string;
    contact_name?: string;
    created_at: string;
    updated_at: string;
  }[]
> {
  const response = await apiClient.get<
    {
      id: string;
      ref_number: string;
      quote_title: string;
      date: string;
      client_name: string;
      contact_name?: string;
      created_at: string;
      updated_at: string;
    }[]
  >(`/api/v1/costing-sheets`, { params });
  return response.data;
}

/**
 * @purpose Retrieves a specific costing sheet by its ID.
 * @param sheetId The unique identifier of the costing sheet.
 * @returns A Promise that resolves to the costing sheet object.
 * @owner Gemini
 */
export async function getCostingSheet(
  sheetId: string,
): Promise<{
  id: string;
  user_id: string;
  ref_number: string;
  date: string;
  quote_title: string;
  organisation_id?: string;
  client_name: string;
  contact_id?: string;
  contact_name?: string;
  contact_email?: string;
  payment_term?: string;
  quotation_validity_days: number;
  lead_time?: string;
  local_tax?: string;
  warranty?: string;
  notes_and_exclusions?: string;
  terms_and_conditions?: string;
  created_at: string;
  updated_at: string;
  [key: string]: any; // For any other unspecified fields
}> {
  const response = await apiClient.get<
    {
      id: string;
      user_id: string;
      ref_number: string;
      date: string;
      quote_title: string;
      organisation_id?: string;
      client_name: string;
      contact_id?: string;
      contact_name?: string;
      contact_email?: string;
      payment_term?: string;
      quotation_validity_days: number;
      lead_time?: string;
      local_tax?: string;
      warranty?: string;
      notes_and_exclusions?: string;
      terms_and_conditions?: string;
      created_at: string;
      updated_at: string;
      [key: string]: any;
    }
  >(`/api/v1/costing-sheets/${sheetId}`);
  return response.data;
}

/**
 * @purpose Updates an existing costing sheet.
 * @param sheetId The unique identifier of the costing sheet to update.
 * @param data The data to update the costing sheet with.
 * @returns A Promise that resolves to the updated costing sheet object.
 * @owner Gemini
 */
export async function updateCostingSheet(
  sheetId: string,
  data: {
    quote_title?: string;
    date?: string;
    client_name?: string;
    organisation_id?: string;
    contact_id?: string;
    contact_name?: string;
    contact_email?: string;
    payment_term?: string;
    quotation_validity_days?: number;
    lead_time?: string;
    local_tax?: string;
    warranty?: string;
    notes_and_exclusions?: string;
    terms_and_conditions?: string;
    [key: string]: any; // For any other unspecified optional fields
  },
): Promise<{
  id: string;
  user_id: string;
  ref_number: string;
  date: string;
  quote_title: string;
  organisation_id?: string;
  client_name: string;
  contact_id?: string;
  contact_name?: string;
  contact_email?: string;
  payment_term?: string;
  quotation_validity_days: number;
  lead_time?: string;
  local_tax?: string;
  warranty?: string;
  notes_and_exclusions?: string;
  terms_and_conditions?: string;
  created_at: string;
  updated_at: string;
  [key: string]: any; // For any other unspecified fields
}> {
  const response = await apiClient.put<
    {
      id: string;
      user_id: string;
      ref_number: string;
      date: string;
      quote_title: string;
      organisation_id?: string;
      client_name: string;
      contact_id?: string;
      contact_name?: string;
      contact_email?: string;
      payment_term?: string;
      quotation_validity_days: number;
      lead_time?: string;
      local_tax?: string;
      warranty?: string;
      notes_and_exclusions?: string;
      terms_and_conditions?: string;
      created_at: string;
      updated_at: string;
      [key: string]: any;
    }
  >(`/api/v1/costing-sheets/${sheetId}`, data);
  return response.data;
}

/**
 * @purpose Deletes a specific costing sheet by its ID.
 * @param sheetId The unique identifier of the costing sheet to delete.
 * @returns A Promise that resolves when the deletion is successful.
 * @owner Gemini
 */
export async function deleteCostingSheet(sheetId: string): Promise<void> {
  await apiClient.delete(`/api/v1/costing-sheets/${sheetId}`);
}

/**
 * @purpose Duplicates an existing costing sheet.
 * @param sheetId The unique identifier of the costing sheet to duplicate.
 * @returns A Promise that resolves to the newly duplicated costing sheet.
 * @owner Gemini
 */
export async function duplicateCostingSheet(
  sheetId: string,
): Promise<{
  id: string;
  user_id: string;
  ref_number: string;
  date: string;
  quote_title: string;
  organisation_id?: string;
  client_name: string;
  contact_id?: string;
  contact_name?: string;
  contact_email?: string;
  payment_term?: string;
  quotation_validity_days: number;
  lead_time?: string;
  local_tax?: string;
  warranty?: string;
  notes_and_exclusions?: string;
  terms_and_conditions?: string;
  created_at: string;
  updated_at: string;
  [key: string]: any; // For any other unspecified fields
}> {
  const response = await apiClient.post<
    {
      id: string;
      user_id: string;
      ref_number: string;
      date: string;
      quote_title: string;
      organisation_id?: string;
      client_name: string;
      contact_id?: string;
      contact_name?: string;
      contact_email?: string;
      payment_term?: string;
      quotation_validity_days: number;
      lead_time?: string;
      local_tax?: string;
      warranty?: string;
      notes_and_exclusions?: string;
      terms_and_conditions?: string;
      created_at: string;
      updated_at: string;
      [key: string]: any;
    }
  >(`/api/v1/costing-sheets/${sheetId}/duplicate`);
  return response.data;
}

// ── Scenarios ───────────────────────────────────────────

/**
 * @purpose Creates a new scenario for a specific costing sheet.
 * @param sheetId The ID of the costing sheet.
 * @param data The data for creating the new scenario.
 * @returns A promise that resolves to the newly created scenario object.
 * @owner [Gemini]
 */
export async function createScenario(
  sheetId: string,
  data: {
    name: string;
    discount_type?: any;
    discount_value?: any;
    show_gst?: boolean;
    notes_exclusions?: any;
    display_order?: number;
  }
): Promise<{
  id: string;
  costing_sheet_id: string;
  name: string;
  discount_type?: any;
  discount_value?: any;
  show_gst: boolean;
  notes_exclusions?: any;
  display_order: number;
  created_at: string;
  updated_at: string;
  totals?: any;
}> {
  const response = await apiClient.post<
    {
      id: string;
      costing_sheet_id: string;
      name: string;
      discount_type?: any;
      discount_value?: any;
      show_gst: boolean;
      notes_exclusions?: any;
      display_order: number;
      created_at: string;
      updated_at: string;
      totals?: any;
    }
  >(`/api/v1/costing-sheets/${sheetId}/scenarios`, data);
  return response.data;
}

/**
 * @purpose Lists all scenarios associated with a specific costing sheet.
 * @param sheetId The ID of the costing sheet.
 * @returns A promise that resolves to an array of scenario objects.
 * @owner [Gemini]
 */
export async function listScenarios(
  sheetId: string
): Promise<
  {
    id: string;
    costing_sheet_id: string;
    name: string;
    discount_type?: any;
    discount_value?: any;
    show_gst: boolean;
    notes_exclusions?: any;
    display_order: number;
    created_at: string;
    updated_at: string;
    totals?: any;
  }[]
> {
  const response = await apiClient.get<
    {
      id: string;
      costing_sheet_id: string;
      name: string;
      discount_type?: any;
      discount_value?: any;
      show_gst: boolean;
      notes_exclusions?: any;
      display_order: number;
      created_at: string;
      updated_at: string;
      totals?: any;
    }[]
  >(`/api/v1/costing-sheets/${sheetId}/scenarios`);
  return response.data;
}

/**
 * @purpose Retrieves a specific scenario by its ID.
 * @param scenarioId The ID of the scenario to retrieve.
 * @returns A promise that resolves to the scenario object.
 * @owner [Gemini]
 */
export async function getScenario(
  scenarioId: string
): Promise<{
  id: string;
  costing_sheet_id: string;
  name: string;
  discount_type?: any;
  discount_value?: any;
  show_gst: boolean;
  notes_exclusions?: any;
  display_order: number;
  created_at: string;
  updated_at: string;
  totals?: any;
}> {
  const response = await apiClient.get<
    {
      id: string;
      costing_sheet_id: string;
      name: string;
      discount_type?: any;
      discount_value?: any;
      show_gst: boolean;
      notes_exclusions?: any;
      display_order: number;
      created_at: string;
      updated_at: string;
      totals?: any;
    }
  >(`/api/v1/scenarios/${scenarioId}`);
  return response.data;
}

/**
 * @purpose Updates an existing scenario.
 * @param scenarioId The ID of the scenario to update.
 * @param data The partial data for updating the scenario.
 * @returns A promise that resolves to the updated scenario object.
 * @owner [Gemini]
 */
export async function updateScenario(
  scenarioId: string,
  data: {
    name?: any;
    discount_type?: any;
    discount_value?: any;
    show_gst?: any;
    notes_exclusions?: any;
    display_order?: any;
  }
): Promise<{
  id: string;
  costing_sheet_id: string;
  name: string;
  discount_type?: any;
  discount_value?: any;
  show_gst: boolean;
  notes_exclusions?: any;
  display_order: number;
  created_at: string;
  updated_at: string;
  totals?: any;
}> {
  const response = await apiClient.put<
    {
      id: string;
      costing_sheet_id: string;
      name: string;
      discount_type?: any;
      discount_value?: any;
      show_gst: boolean;
      notes_exclusions?: any;
      display_order: number;
      created_at: string;
      updated_at: string;
      totals?: any;
    }
  >(`/api/v1/scenarios/${scenarioId}`, data);
  return response.data;
}

/**
 * @purpose Deletes a scenario by its ID.
 * @param scenarioId The ID of the scenario to delete.
 * @returns A promise that resolves when the scenario is successfully deleted.
 * @owner [Gemini]
 */
export async function deleteScenario(scenarioId: string): Promise<void> {
  await apiClient.delete<void>(`/api/v1/scenarios/${scenarioId}`);
}

/**
 * @purpose Retrieves a preview of a specific scenario, potentially including computed totals or other dynamic data.
 * @param scenarioId The ID of the scenario to preview.
 * @returns A promise that resolves to the scenario preview object.
 * @owner [Gemini]
 */
export async function previewScenario(
  scenarioId: string
): Promise<{
  id: string;
  costing_sheet_id: string;
  name: string;
  discount_type?: any;
  discount_value?: any;
  show_gst: boolean;
  notes_exclusions?: any;
  display_order: number;
  created_at: string;
  updated_at: string;
  totals?: any;
}> {
  const response = await apiClient.get<
    {
      id: string;
      costing_sheet_id: string;
      name: string;
      discount_type?: any;
      discount_value?: any;
      show_gst: boolean;
      notes_exclusions?: any;
      display_order: number;
      created_at: string;
      updated_at: string;
      totals?: any;
    }
  >(`/api/v1/scenarios/${scenarioId}/preview`);
  return response.data;
}

// ── Line Items ───────────────────────────────────────────

/**
 * @purpose Creates a new line item within a specific scenario.
 * @param scenarioId The ID of the scenario to which the line item will be added.
 * @param data The data for the new line item.
 * @returns A promise that resolves to the created line item.
 * @owner Gemini
 */
export async function createLineItem(
  scenarioId: string,
  data: {
    section: string;
    description: string;
    sub_specs?: string | null;
    qty?: string | null;
    unit?: string;
    cost_rate?: string | null;
    cost_currency?: string;
    markup_pct?: string | null;
    contingency_pct?: string | null;
    is_visible?: boolean;
    is_bundle_parent?: boolean;
    parent_line_item_id?: string | null;
    display_order?: number;
  }
): Promise<{
  id: string;
  scenario_id: string;
  parent_line_item_id?: string | null;
  section: string;
  display_order: number;
  description: string;
  sub_specs?: string | null;
  qty: string;
  unit: string;
  cost_rate: string;
  cost_currency: string;
  markup_pct: string;
  contingency_pct: string;
  is_visible: boolean;
  is_bundle_parent: boolean;
  bundle_override_price?: string | null;
  created_at: string;
  updated_at: string;
}> {
  const response = await apiClient.post<{
    id: string;
    scenario_id: string;
    parent_line_item_id?: string | null;
    section: string;
    display_order: number;
    description: string;
    sub_specs?: string | null;
    qty: string;
    unit: string;
    cost_rate: string;
    cost_currency: string;
    markup_pct: string;
    contingency_pct: string;
    is_visible: boolean;
    is_bundle_parent: boolean;
    bundle_override_price?: string | null;
    created_at: string;
    updated_at: string;
  }>(`/api/v1/scenarios/${scenarioId}/line-items`, data);
  return response.data;
}

/**
 * @purpose Lists all line items for a given scenario.
 * @param scenarioId The ID of the scenario to retrieve line items from.
 * @returns A promise that resolves to an array of line items.
 * @owner Gemini
 */
export async function listLineItems(
  scenarioId: string
): Promise<
  {
    id: string;
    scenario_id: string;
    parent_line_item_id?: string | null;
    section: string;
    display_order: number;
    description: string;
    sub_specs?: string | null;
    qty: string;
    unit: string;
    cost_rate: string;
    cost_currency: string;
    markup_pct: string;
    contingency_pct: string;
    is_visible: boolean;
    is_bundle_parent: boolean;
    bundle_override_price?: string | null;
    created_at: string;
    updated_at: string;
  }[]
> {
  const response = await apiClient.get<
    {
      id: string;
      scenario_id: string;
      parent_line_item_id?: string | null;
      section: string;
      display_order: number;
      description: string;
      sub_specs?: string | null;
      qty: string;
      unit: string;
      cost_rate: string;
      cost_currency: string;
      markup_pct: string;
      contingency_pct: string;
      is_visible: boolean;
      is_bundle_parent: boolean;
      bundle_override_price?: string | null;
      created_at: string;
      updated_at: string;
    }[]
  >(`/api/v1/scenarios/${scenarioId}/line-items`);
  return response.data;
}

/**
 * @purpose Retrieves a single line item by its ID.
 * @param lineItemId The ID of the line item to retrieve.
 * @returns A promise that resolves to the retrieved line item.
 * @owner Gemini
 */
export async function getLineItem(
  lineItemId: string
): Promise<{
  id: string;
  scenario_id: string;
  parent_line_item_id?: string | null;
  section: string;
  display_order: number;
  description: string;
  sub_specs?: string | null;
  qty: string;
  unit: string;
  cost_rate: string;
  cost_currency: string;
  markup_pct: string;
  contingency_pct: string;
  is_visible: boolean;
  is_bundle_parent: boolean;
  bundle_override_price?: string | null;
  created_at: string;
  updated_at: string;
}> {
  const response = await apiClient.get<{
    id: string;
    scenario_id: string;
    parent_line_item_id?: string | null;
    section: string;
    display_order: number;
    description: string;
    sub_specs?: string | null;
    qty: string;
    unit: string;
    cost_rate: string;
    cost_currency: string;
    markup_pct: string;
    contingency_pct: string;
    is_visible: boolean;
    is_bundle_parent: boolean;
    bundle_override_price?: string | null;
    created_at: string;
    updated_at: string;
  }>(`/api/v1/line-items/${lineItemId}`);
  return response.data;
}

/**
 * @purpose Updates an existing line item.
 * @param lineItemId The ID of the line item to update.
 * @param data The data to update the line item with.
 * @returns A promise that resolves to the updated line item.
 * @owner Gemini
 */
export async function updateLineItem(
  lineItemId: string,
  data: {
    description?: string | null;
    sub_specs?: string | null;
    qty?: string | null;
    unit?: string | null;
    cost_rate?: string | null;
    cost_currency?: string | null;
    markup_pct?: string | null;
    contingency_pct?: string | null;
    is_visible?: boolean | null;
    section?: string | null;
    display_order?: number | null;
  }
): Promise<{
  id: string;
  scenario_id: string;
  parent_line_item_id?: string | null;
  section: string;
  display_order: number;
  description: string;
  sub_specs?: string | null;
  qty: string;
  unit: string;
  cost_rate: string;
  cost_currency: string;
  markup_pct: string;
  contingency_pct: string;
  is_visible: boolean;
  is_bundle_parent: boolean;
  bundle_override_price?: string | null;
  created_at: string;
  updated_at: string;
}> {
  const response = await apiClient.put<{
    id: string;
    scenario_id: string;
    parent_line_item_id?: string | null;
    section: string;
    display_order: number;
    description: string;
    sub_specs?: string | null;
    qty: string;
    unit: string;
    cost_rate: string;
    cost_currency: string;
    markup_pct: string;
    contingency_pct: string;
    is_visible: boolean;
    is_bundle_parent: boolean;
    bundle_override_price?: string | null;
    created_at: string;
    updated_at: string;
  }>(`/api/v1/line-items/${lineItemId}`, data);
  return response.data;
}

/**
 * @purpose Deletes a line item by its ID.
 * @param lineItemId The ID of the line item to delete.
 * @returns A promise that resolves when the line item is deleted.
 * @owner Gemini
 */
export async function deleteLineItem(lineItemId: string): Promise<void> {
  await apiClient.delete<void>(`/api/v1/line-items/${lineItemId}`);
}

/**
 * @purpose Adds a component to a bundle line item.
 * @param lineItemId The ID of the parent bundle line item.
 * @param data The data for the new bundle component line item.
 * @returns A promise that resolves to the created bundle component line item.
 * @owner Gemini
 */
export async function addBundleComponent(
  lineItemId: string,
  data: {
    section: string;
    description: string;
    sub_specs?: string | null;
    qty?: string | null;
    unit?: string;
    cost_rate?: string | null;
    cost_currency?: string;
    markup_pct?: string | null;
    contingency_pct?: string | null;
    is_visible?: boolean;
    is_bundle_parent?: boolean;
    parent_line_item_id?: string | null;
    display_order?: number;
  }
): Promise<{
  id: string;
  scenario_id: string;
  parent_line_item_id?: string | null;
  section: string;
  display_order: number;
  description: string;
  sub_specs?: string | null;
  qty: string;
  unit: string;
  cost_rate: string;
  cost_currency: string;
  markup_pct: string;
  contingency_pct: string;
  is_visible: boolean;
  is_bundle_parent: boolean;
  bundle_override_price?: string | null;
  created_at: string;
  updated_at: string;
}> {
  const response = await apiClient.post<{
    id: string;
    scenario_id: string;
    parent_line_item_id?: string | null;
    section: string;
    display_order: number;
    description: string;
    sub_specs?: string | null;
    qty: string;
    unit: string;
    cost_rate: string;
    cost_currency: string;
    markup_pct: string;
    contingency_pct: string;
    is_visible: boolean;
    is_bundle_parent: boolean;
    bundle_override_price?: string | null;
    created_at: string;
    updated_at: string;
  }>(`/api/v1/line-items/${lineItemId}/bundle-components`, data);
  return response.data;
}

/**
 * @purpose Sets the bundle override price for a line item.
 * @param lineItemId The ID of the line item to set the bundle override on.
 * @param data The bundle override price data.
 * @returns A promise that resolves to the updated line item.
 * @owner Gemini
 */
export async function setBundleOverride(
  lineItemId: string,
  data: { bundle_override_price?: string | null }
): Promise<{
  id: string;
  scenario_id: string;
  parent_line_item_id?: string | null;
  section: string;
  display_order: number;
  description: string;
  sub_specs?: string | null;
  qty: string;
  unit: string;
  cost_rate: string;
  cost_currency: string;
  markup_pct: string;
  contingency_pct: string;
  is_visible: boolean;
  is_bundle_parent: boolean;
  bundle_override_price?: string | null;
  created_at: string;
  updated_at: string;
}> {
  const response = await apiClient.patch<{
    id: string;
    scenario_id: string;
    parent_line_item_id?: string | null;
    section: string;
    display_order: number;
    description: string;
    sub_specs?: string | null;
    qty: string;
    unit: string;
    cost_rate: string;
    cost_currency: string;
    markup_pct: string;
    contingency_pct: string;
    is_visible: boolean;
    is_bundle_parent: boolean;
    bundle_override_price?: string | null;
    created_at: string;
    updated_at: string;
  }>(`/api/v1/line-items/${lineItemId}/bundle-override`, data);
  return response.data;
}

/**
 * @purpose Reorders line items within a scenario.
 * @param scenarioId The ID of the scenario containing the line items to reorder.
 * @param data An array of objects, each containing the ID and new display order for a line item.
 * @returns A promise that resolves when the line items have been reordered.
 * @owner Gemini
 */
export async function reorderLineItems(
  scenarioId: string,
  data: {
    items: {
      id: string;
      display_order: number;
    }[];
  }
): Promise<void> {
  await apiClient.put<void>(`/api/v1/scenarios/${scenarioId}/line-items/reorder`, data);
}

// ── FX & TNC Additions ───────────────────────────────────────────

/**
 * @purpose Get live foreign exchange rates.
 * @param {string | undefined} base - The base currency for the rates (e.g., "USD").
 * @returns {Promise<{ base: string; rates: Record<string, number>; cached: boolean }>} An object containing the base currency, exchange rates, and a flag indicating if the data is cached.
 * @owner [Gemini]
 */
export async function getLiveFxRates(
  base?: string
): Promise<{ base: string; rates: Record<string, number>; cached: boolean }> {
  const response = await apiClient.get<{ base: string; rates: Record<string, number>; cached: boolean }>(
    `/api/v1/fx/live-rates`,
    {
      params: { base },
    }
  );
  return response.data;
}

/**
 * @purpose List FX overrides for a specific costing sheet.
 * @param {string} sheetId - The ID of the costing sheet.
 * @returns {Promise<Array<{ id: string; costing_sheet_id: string; base_currency: string; target_currency: string; override_rate: string; created_at: string; updated_at: string }>>} An array of FX override objects.
 * @owner [Gemini]
 */
export async function listFxOverrides(
  sheetId: string
): Promise<
  Array<{
    id: string;
    costing_sheet_id: string;
    base_currency: string;
    target_currency: string;
    override_rate: string;
    created_at: string;
    updated_at: string;
  }>
> {
  const response = await apiClient.get<
    Array<{
      id: string;
      costing_sheet_id: string;
      base_currency: string;
      target_currency: string;
      override_rate: string;
      created_at: string;
      updated_at: string;
    }>
  >(`/api/v1/costing-sheets/${sheetId}/fx-overrides`);
  return response.data;
}

/**
 * @purpose Create a new FX override for a specific costing sheet.
 * @param {string} sheetId - The ID of the costing sheet.
 * @param {{ base_currency: string; target_currency?: string; override_rate: number }} data - The data for the new FX override.
 * @returns {Promise<any>} The created FX override object.
 * @owner [Gemini]
 */
export async function createFxOverride(
  sheetId: string,
  data: { base_currency: string; target_currency?: string; override_rate: number }
): Promise<any> {
  const response = await apiClient.post<any>(
    `/api/v1/costing-sheets/${sheetId}/fx-overrides`,
    data
  );
  return response.data;
}

/**
 * @purpose Update an existing FX override.
 * @param {string} overrideId - The ID of the FX override to update.
 * @param {{ override_rate: number }} data - The data to update the FX override with.
 * @returns {Promise<{ id: string; costing_sheet_id: string; base_currency: string; target_currency: string; override_rate: string; created_at: string; updated_at: string }>} The updated FX override object.
 * @owner [Gemini]
 */
export async function updateFxOverride(
  overrideId: string,
  data: { override_rate: number }
): Promise<{
  id: string;
  costing_sheet_id: string;
  base_currency: string;
  target_currency: string;
  override_rate: string;
  created_at: string;
  updated_at: string;
}> {
  const response = await apiClient.put<
    {
      id: string;
      costing_sheet_id: string;
      base_currency: string;
      target_currency: string;
      override_rate: string;
      created_at: string;
      updated_at: string;
    }
  >(`/api/v1/fx-overrides/${overrideId}`, data);
  return response.data;
}

/**
 * @purpose Delete an FX override.
 * @param {string} overrideId - The ID of the FX override to delete.
 * @returns {Promise<void>}
 * @owner [Gemini]
 */
export async function deleteFxOverride(overrideId: string): Promise<void> {
  await apiClient.delete<void>(`/api/v1/fx-overrides/${overrideId}`);
}

/**
 * @purpose List terms and conditions additions for a specific costing sheet.
 * @param {string} sheetId - The ID of the costing sheet.
 * @returns {Promise<Array<{ id: string; bullet_point: string; display_order: number; costing_sheet_id?: string; created_at: string; updated_at: string }>>} An array of T&C addition objects.
 * @owner [Gemini]
 */
export async function listSheetTnc(
  sheetId: string
): Promise<
  Array<{
    id: string;
    bullet_point: string;
    display_order: number;
    costing_sheet_id?: string;
    created_at: string;
    updated_at: string;
  }>
> {
  const response = await apiClient.get<
    Array<{
      id: string;
      bullet_point: string;
      display_order: number;
      costing_sheet_id?: string;
      created_at: string;
      updated_at: string;
    }>
  >(`/api/v1/costing-sheets/${sheetId}/tnc-additions`);
  return response.data;
}

/**
 * @purpose Create a new terms and conditions addition for a specific costing sheet.
 * @param {string} sheetId - The ID of the costing sheet.
 * @param {{ bullet_point: string; display_order?: number }} data - The data for the new T&C addition.
 * @returns {Promise<any>} The created T&C addition object.
 * @owner [Gemini]
 */
export async function createSheetTnc(
  sheetId: string,
  data: { bullet_point: string; display_order?: number }
): Promise<any> {
  const response = await apiClient.post<any>(
    `/api/v1/costing-sheets/${sheetId}/tnc-additions`,
    data
  );
  return response.data;
}

/**
 * @purpose Update an existing terms and conditions addition.
 * @param {string} tncId - The ID of the T&C addition to update.
 * @param {{ bullet_point?: string; display_order?: number }} data - The data to update the T&C addition with.
 * @returns {Promise<{ id: string; bullet_point: string; display_order: number; costing_sheet_id?: string; created_at: string; updated_at: string }>} The updated T&C addition object.
 * @owner [Gemini]
 */
export async function updateSheetTnc(
  tncId: string,
  data: { bullet_point?: string; display_order?: number }
): Promise<{
  id: string;
  bullet_point: string;
  display_order: number;
  costing_sheet_id?: string;
  created_at: string;
  updated_at: string;
}> {
  const response = await apiClient.put<
    {
      id: string;
      bullet_point: string;
      display_order: number;
      costing_sheet_id?: string;
      created_at: string;
      updated_at: string;
    }
  >(`/api/v1/tnc-additions/${tncId}`, data);
  return response.data;
}

/**
 * @purpose Delete a terms and conditions addition.
 * @param {string} tncId - The ID of the T&C addition to delete.
 * @returns {Promise<void>}
 * @owner [Gemini]
 */
export async function deleteSheetTnc(tncId: string): Promise<void> {
  await apiClient.delete<void>(`/api/v1/tnc-additions/${tncId}`);
}
// ── Exports & Products ───────────────────────────────────────────

/**
 * @purpose Creates a new export for a specific scenario.
 * @param scenarioId The ID of the scenario for which to create the export.
 * @param data The data for creating the export, including the file type.
 * @returns A Promise that resolves to the created export object.
 * @owner [Gemini]
 */
export async function createExport(
  scenarioId: string,
  data: {
    file_type: string;
  }
): Promise<{
  id: string;
  costing_sheet_id: string;
  scenario_id: string;
  user_id: string;
  revision_number: number;
  file_type: string;
  file_path: string;
  exported_at: string;
}> {
  const response = await apiClient.post(
    `/api/v1/scenarios/${scenarioId}/exports`,
    data
  );
  return response.data;
}

/**
 * @purpose Lists all exports associated with a specific scenario.
 * @param scenarioId The ID of the scenario to list exports for.
 * @returns A Promise that resolves to an array of export objects.
 * @owner [Gemini]
 */
export async function listScenarioExports(
  scenarioId: string
): Promise<
  {
    id: string;
    costing_sheet_id: string;
    scenario_id: string;
    user_id: string;
    revision_number: number;
    file_type: string;
    file_path: string;
    exported_at: string;
  }[]
> {
  const response = await apiClient.get(
    `/api/v1/scenarios/${scenarioId}/exports`
  );
  return response.data;
}

/**
 * @purpose Lists all exports associated with a specific costing sheet.
 * @param sheetId The ID of the costing sheet to list exports for.
 * @returns A Promise that resolves to an array of export objects.
 * @owner [Gemini]
 */
export async function listSheetExports(
  sheetId: string
): Promise<
  {
    id: string;
    costing_sheet_id: string;
    scenario_id: string;
    user_id: string;
    revision_number: number;
    file_type: string;
    file_path: string;
    exported_at: string;
  }[]
> {
  const response = await apiClient.get(
    `/api/v1/costing-sheets/${sheetId}/exports`
  );
  return response.data;
}

/**
 * @purpose Retrieves a signed URL to download a specific export.
 * @param exportId The ID of the export to download.
 * @returns A Promise that resolves to an object containing the signed URL and other download details.
 * @owner [Gemini]
 */
export async function downloadExport(
  exportId: string
): Promise<{
  export_id: string;
  signed_url: string;
  expires_in_seconds: number;
  file_type: string;
  revision_number: number;
}> {
  const response = await apiClient.get(
    `/api/v1/exports/${exportId}/download`
  );
  return response.data;
}

/**
 * @purpose Deletes a specific export.
 * @param exportId The ID of the export to delete.
 * @returns A Promise that resolves when the export is successfully deleted.
 * @owner [Gemini]
 */
export async function deleteExport(exportId: string): Promise<void> {
  await apiClient.delete(
    `/api/v1/exports/${exportId}`
  );
}

/**
 * @purpose Lists products, optionally filtered by category or name.
 * @param params Optional query parameters for filtering products (category, name).
 * @returns A Promise that resolves to an array of product objects.
 * @owner [Gemini]
 */
export async function listProducts(
  params?: {
    category?: string;
    name?: string;
  }
): Promise<
  {
    id: string;
    category: string;
    name: string;
    description?: string;
    sub_specs?: string;
    default_cost_price: string;
    default_currency: string;
    default_unit: string;
    default_markup_pct: string;
    default_contingency_pct: string;
    created_at: string;
    updated_at: string;
  }[]
> {
  const response = await apiClient.get(
    `/api/v1/products`,
    { params }
  );
  return response.data;
}

/**
 * @purpose Creates a new product.
 * @param data The data for creating the new product.
 * @returns A Promise that resolves to the created product object.
 * @owner [Gemini]
 */
export async function createProduct(
  data: {
    category: string;
    name: string;
    description?: string;
    sub_specs?: string;
    default_cost_price?: string;
    default_currency?: string;
    default_unit?: string;
    default_markup_pct?: string;
    default_contingency_pct?: string;
  }
): Promise<{
  id: string;
  category: string;
  name: string;
  description?: string;
  sub_specs?: string;
  default_cost_price: string;
  default_currency: string;
  default_unit: string;
  default_markup_pct: string;
  default_contingency_pct: string;
  created_at: string;
  updated_at: string;
}> {
  const response = await apiClient.post(
    `/api/v1/products`,
    data
  );
  return response.data;
}

/**
 * @purpose Retrieves a specific product by its ID.
 * @param productId The ID of the product to retrieve.
 * @returns A Promise that resolves to the product object.
 * @owner [Gemini]
 */
export async function getProduct(
  productId: string
): Promise<{
  id: string;
  category: string;
  name: string;
  description?: string;
  sub_specs?: string;
  default_cost_price: string;
  default_currency: string;
  default_unit: string;
  default_markup_pct: string;
  default_contingency_pct: string;
  created_at: string;
  updated_at: string;
}> {
  const response = await apiClient.get(
    `/api/v1/products/${productId}`
  );
  return response.data;
}

/**
 * @purpose Updates an existing product.
 * @param productId The ID of the product to update.
 * @param data The data to update the product with.
 * @returns A Promise that resolves to the updated product object.
 * @owner [Gemini]
 */
export async function updateProduct(
  productId: string,
  data: {
    category?: string;
    name?: string;
    description?: string;
    sub_specs?: string;
    default_cost_price?: string;
    default_currency?: string;
    default_unit?: string;
    default_markup_pct?: string;
    default_contingency_pct?: string;
  }
): Promise<{
  id: string;
  category: string;
  name: string;
  description?: string;
  sub_specs?: string;
  default_cost_price: string;
  default_currency: string;
  default_unit: string;
  default_markup_pct: string;
  default_contingency_pct: string;
  created_at: string;
  updated_at: string;
}> {
  const response = await apiClient.put(
    `/api/v1/products/${productId}`,
    data
  );
  return response.data;
}

/**
 * @purpose Deletes a specific product.
 * @param productId The ID of the product to delete.
 * @returns A Promise that resolves when the product is successfully deleted.
 * @owner [Gemini]
 */
export async function deleteProduct(productId: string): Promise<void> {
  await apiClient.delete(
    `/api/v1/products/${productId}`
  );
}

// ── Templates & Settings ───────────────────────────────────────────

/**
 * @purpose Lists all available scenario templates.
 * @returns {Promise<Array<{
 *   id: string;
 *   name: string;
 *   notes_exclusions?: any;
 *   template_line_items?: Array<{
 *     id: string;
 *     scenario_template_id: string;
 *     parent_template_line_item_id?: string | null;
 *     section: string;
 *     display_order: number;
 *     description: string;
 *     sub_specs?: any;
 *     qty: string;
 *     unit: string;
 *     cost_rate: string;
 *     cost_currency: string;
 *     markup_pct: string;
 *     contingency_pct: string;
 *     is_visible: boolean;
 *     is_bundle_parent: boolean;
 *     bundle_override_price?: string | null;
 *     created_at: string;
 *     updated_at: string;
 *   }>;
 *   created_at: string;
 *   updated_at: string;
 * }>>} A promise that resolves to an array of scenario templates.
 * @owner Gemini
 */
export async function listTemplates(): Promise<Array<{
  id: string;
  name: string;
  notes_exclusions?: any;
  template_line_items?: Array<{
    id: string;
    scenario_template_id: string;
    parent_template_line_item_id?: string | null;
    section: string;
    display_order: number;
    description: string;
    sub_specs?: any;
    qty: string;
    unit: string;
    cost_rate: string;
    cost_currency: string;
    markup_pct: string;
    contingency_pct: string;
    is_visible: boolean;
    is_bundle_parent: boolean;
    bundle_override_price?: string | null;
    created_at: string;
    updated_at: string;
  }>;
  created_at: string;
  updated_at: string;
}>> {
  const response = await apiClient.get<Array<{
    id: string;
    name: string;
    notes_exclusions?: any;
    template_line_items?: Array<{
      id: string;
      scenario_template_id: string;
      parent_template_line_item_id?: string | null;
      section: string;
      display_order: number;
      description: string;
      sub_specs?: any;
      qty: string;
      unit: string;
      cost_rate: string;
      cost_currency: string;
      markup_pct: string;
      contingency_pct: string;
      is_visible: boolean;
      is_bundle_parent: boolean;
      bundle_override_price?: string | null;
      created_at: string;
      updated_at: string;
    }>;
    created_at: string;
    updated_at: string;
  }>>('/api/v1/scenario-templates');
  return response.data;
}

/**
 * @purpose Creates a new scenario template.
 * @param {object} data - The data for the new template.
 * @param {string} data.name - The name of the template.
 * @param {any} [data.notes_exclusions] - Optional notes and exclusions for the template.
 * @returns {Promise<{
 *   id: string;
 *   name: string;
 *   notes_exclusions?: any;
 *   template_line_items?: Array<{
 *     id: string;
 *     scenario_template_id: string;
 *     parent_template_line_item_id?: string | null;
 *     section: string;
 *     display_order: number;
 *     description: string;
 *     sub_specs?: any;
 *     qty: string;
 *     unit: string;
 *     cost_rate: string;
 *     cost_currency: string;
 *     markup_pct: string;
 *     contingency_pct: string;
 *     is_visible: boolean;
 *     is_bundle_parent: boolean;
 *     bundle_override_price?: string | null;
 *     created_at: string;
 *     updated_at: string;
 *   }>;
 *   created_at: string;
 *   updated_at: string;
 * }>} A promise that resolves to the created template object.
 * @owner Gemini
 */
export async function createTemplate(data: {
  name: string;
  notes_exclusions?: any;
}): Promise<{
  id: string;
  name: string;
  notes_exclusions?: any;
  template_line_items?: Array<{
    id: string;
    scenario_template_id: string;
    parent_template_line_item_id?: string | null;
    section: string;
    display_order: number;
    description: string;
    sub_specs?: any;
    qty: string;
    unit: string;
    cost_rate: string;
    cost_currency: string;
    markup_pct: string;
    contingency_pct: string;
    is_visible: boolean;
    is_bundle_parent: boolean;
    bundle_override_price?: string | null;
    created_at: string;
    updated_at: string;
  }>;
  created_at: string;
  updated_at: string;
}> {
  const response = await apiClient.post<{
    id: string;
    name: string;
    notes_exclusions?: any;
    template_line_items?: Array<{
      id: string;
      scenario_template_id: string;
      parent_template_line_item_id?: string | null;
      section: string;
      display_order: number;
      description: string;
      sub_specs?: any;
      qty: string;
      unit: string;
      cost_rate: string;
      cost_currency: string;
      markup_pct: string;
      contingency_pct: string;
      is_visible: boolean;
      is_bundle_parent: boolean;
      bundle_override_price?: string | null;
      created_at: string;
      updated_at: string;
    }>;
    created_at: string;
    updated_at: string;
  }>('/api/v1/scenario-templates', data);
  return response.data;
}

/**
 * @purpose Retrieves a specific scenario template by its ID.
 * @param {string} templateId - The unique identifier of the template.
 * @returns {Promise<{
 *   id: string;
 *   name: string;
 *   notes_exclusions?: any;
 *   template_line_items?: Array<{
 *     id: string;
 *     scenario_template_id: string;
 *     parent_template_line_item_id?: string | null;
 *     section: string;
 *     display_order: number;
 *     description: string;
 *     sub_specs?: any;
 *     qty: string;
 *     unit: string;
 *     cost_rate: string;
 *     cost_currency: string;
 *     markup_pct: string;
 *     contingency_pct: string;
 *     is_visible: boolean;
 *     is_bundle_parent: boolean;
 *     bundle_override_price?: string | null;
 *     created_at: string;
 *     updated_at: string;
 *   }>;
 *   created_at: string;
 *   updated_at: string;
 * }>} A promise that resolves to the template object.
 * @owner Gemini
 */
export async function getTemplate(templateId: string): Promise<{
  id: string;
  name: string;
  notes_exclusions?: any;
  template_line_items?: Array<{
    id: string;
    scenario_template_id: string;
    parent_template_line_item_id?: string | null;
    section: string;
    display_order: number;
    description: string;
    sub_specs?: any;
    qty: string;
    unit: string;
    cost_rate: string;
    cost_currency: string;
    markup_pct: string;
    contingency_pct: string;
    is_visible: boolean;
    is_bundle_parent: boolean;
    bundle_override_price?: string | null;
    created_at: string;
    updated_at: string;
  }>;
  created_at: string;
  updated_at: string;
}> {
  const response = await apiClient.get<{
    id: string;
    name: string;
    notes_exclusions?: any;
    template_line_items?: Array<{
      id: string;
      scenario_template_id: string;
      parent_template_line_item_id?: string | null;
      section: string;
      display_order: number;
      description: string;
      sub_specs?: any;
      qty: string;
      unit: string;
      cost_rate: string;
      cost_currency: string;
      markup_pct: string;
      contingency_pct: string;
      is_visible: boolean;
      is_bundle_parent: boolean;
      bundle_override_price?: string | null;
      created_at: string;
      updated_at: string;
    }>;
    created_at: string;
    updated_at: string;
  }>(`/api/v1/scenario-templates/${templateId}`);
  return response.data;
}

/**
 * @purpose Updates an existing scenario template.
 * @param {string} templateId - The unique identifier of the template to update.
 * @param {object} data - The update data for the template.
 * @param {any} [data.name] - Optional new name for the template.
 * @param {any} [data.notes_exclusions] - Optional new notes and exclusions for the template.
 * @returns {Promise<{
 *   id: string;
 *   name: string;
 *   notes_exclusions?: any;
 *   template_line_items?: Array<{
 *     id: string;
 *     scenario_template_id: string;
 *     parent_template_line_item_id?: string | null;
 *     section: string;
 *     display_order: number;
 *     description: string;
 *     sub_specs?: any;
 *     qty: string;
 *     unit: string;
 *     cost_rate: string;
 *     cost_currency: string;
 *     markup_pct: string;
 *     contingency_pct: string;
 *     is_visible: boolean;
 *     is_bundle_parent: boolean;
 *     bundle_override_price?: string | null;
 *     created_at: string;
 *     updated_at: string;
 *   }>;
 *   created_at: string;
 *   updated_at: string;
 * }>} A promise that resolves to the updated template object.
 * @owner Gemini
 */
export async function updateTemplate(templateId: string, data: {
  name?: any;
  notes_exclusions?: any;
}): Promise<{
  id: string;
  name: string;
  notes_exclusions?: any;
  template_line_items?: Array<{
    id: string;
    scenario_template_id: string;
    parent_template_line_item_id?: string | null;
    section: string;
    display_order: number;
    description: string;
    sub_specs?: any;
    qty: string;
    unit: string;
    cost_rate: string;
    cost_currency: string;
    markup_pct: string;
    contingency_pct: string;
    is_visible: boolean;
    is_bundle_parent: boolean;
    bundle_override_price?: string | null;
    created_at: string;
    updated_at: string;
  }>;
  created_at: string;
  updated_at: string;
}> {
  const response = await apiClient.put<{
    id: string;
    name: string;
    notes_exclusions?: any;
    template_line_items?: Array<{
      id: string;
      scenario_template_id: string;
      parent_template_line_item_id?: string | null;
      section: string;
      display_order: number;
      description: string;
      sub_specs?: any;
      qty: string;
      unit: string;
      cost_rate: string;
      cost_currency: string;
      markup_pct: string;
      contingency_pct: string;
      is_visible: boolean;
      is_bundle_parent: boolean;
      bundle_override_price?: string | null;
      created_at: string;
      updated_at: string;
    }>;
    created_at: string;
    updated_at: string;
  }>(`/api/v1/scenario-templates/${templateId}`, data);
  return response.data;
}

/**
 * @purpose Deletes a scenario template by its ID.
 * @param {string} templateId - The unique identifier of the template to delete.
 * @returns {Promise<void>} A promise that resolves when the template is successfully deleted.
 * @owner Gemini
 */
export async function deleteTemplate(templateId: string): Promise<void> {
  await apiClient.delete<void>(`/api/v1/scenario-templates/${templateId}`);
}

/**
 * @purpose Applies a scenario template to a costing sheet, creating new scenarios and line items based on the template.
 * @param {string} templateId - The unique identifier of the template to apply.
 * @param {string} sheetId - The unique identifier of the costing sheet to apply the template to.
 * @returns {Promise<void>} A promise that resolves when the template is successfully applied.
 * @owner Gemini
 */
export async function applyTemplate(templateId: string, sheetId: string): Promise<void> {
  await apiClient.post<void>(`/api/v1/scenario-templates/${templateId}/apply/${sheetId}`);
}

/**
 * @purpose Retrieves all system settings.
 * @returns {Promise<Array<{
 *   id: string;
 *   key: string;
 *   value: any;
 *   created_at: string;
 *   updated_at: string;
 * }>>} A promise that resolves to an array of setting objects.
 * @owner Gemini
 */
export async function getSettings(): Promise<Array<{
  id: string;
  key: string;
  value: any;
  created_at: string;
  updated_at: string;
}>> {
  const response = await apiClient.get<Array<{
    id: string;
    key: string;
    value: any;
    created_at: string;
    updated_at: string;
  }>>('/api/v1/settings');
  return response.data;
}

/**
 * @purpose Updates a specific system setting by its key.
 * @param {string} key - The key of the setting to update.
 * @param {any} value - The new value for the setting.
 * @returns {Promise<{
 *   id: string;
 *   key: string;
 *   value: any;
 *   created_at: string;
 *   updated_at: string;
 * }>} A promise that resolves to the updated setting object.
 * @owner Gemini
 */
export async function updateSetting(key: string, value: any): Promise<{
  id: string;
  key: string;
  value: any;
  created_at: string;
  updated_at: string;
}> {
  const response = await apiClient.put<{
    id: string;
    key: string;
    value: any;
    created_at: string;
    updated_at: string;
  }>(`/api/v1/settings/${key}`, { value });
  return response.data;
}

/**
 * @purpose Lists all global Terms & Conditions additions.
 * @returns {Promise<Array<{
 *   id: string;
 *   bullet_point: string;
 *   display_order: number;
 *   costing_sheet_id?: any;
 *   created_at: string;
 *   updated_at: string;
 * }>>} A promise that resolves to an array of global TNC additions.
 * @owner Gemini
 */
export async function listGlobalTnc(): Promise<Array<{
  id: string;
  bullet_point: string;
  display_order: number;
  costing_sheet_id?: any;
  created_at: string;
  updated_at: string;
}>> {
  const response = await apiClient.get<Array<{
    id: string;
    bullet_point: string;
    display_order: number;
    costing_sheet_id?: any;
    created_at: string;
    updated_at: string;
  }>>('/api/v1/settings/tnc-additions');
  return response.data;
}

/**
 * @purpose Creates a new global Terms & Conditions addition.
 * @param {object} data - The data for the new TNC addition.
 * @param {string} data.bullet_point - The text of the TNC bullet point.
 * @param {number} [data.display_order] - Optional display order for the TNC.
 * @returns {Promise<{
 *   id: string;
 *   bullet_point: string;
 *   display_order: number;
 *   costing_sheet_id?: any;
 *   created_at: string;
 *   updated_at: string;
 * }>} A promise that resolves to the created global TNC addition object.
 * @owner Gemini
 */
export async function createGlobalTnc(data: {
  bullet_point: string;
  display_order?: number;
}): Promise<{
  id: string;
  bullet_point: string;
  display_order: number;
  costing_sheet_id?: any;
  created_at: string;
  updated_at: string;
}> {
  const response = await apiClient.post<{
    id: string;
    bullet_point: string;
    display_order: number;
    costing_sheet_id?: any;
    created_at: string;
    updated_at: string;
  }>('/api/v1/settings/tnc-additions', data);
  return response.data;
}

/**
 * @purpose Updates an existing global Terms & Conditions addition.
 * @param {string} tncId - The unique identifier of the TNC addition to update.
 * @param {object} data - The update data for the TNC addition.
 * @param {any} [data.bullet_point] - Optional new text for the TNC bullet point.
 * @param {any} [data.display_order] - Optional new display order for the TNC.
 * @returns {Promise<{
 *   id: string;
 *   bullet_point: string;
 *   display_order: number;
 *   costing_sheet_id?: any;
 *   created_at: string;
 *   updated_at: string;
 * }>} A promise that resolves to the updated global TNC addition object.
 * @owner Gemini
 */
export async function updateGlobalTnc(tncId: string, data: {
  bullet_point?: any;
  display_order?: any;
}): Promise<{
  id: string;
  bullet_point: string;
  display_order: number;
  costing_sheet_id?: any;
  created_at: string;
  updated_at: string;
}> {
  const response = await apiClient.put<{
    id: string;
    bullet_point: string;
    display_order: number;
    costing_sheet_id?: any;
    created_at: string;
    updated_at: string;
  }>(`/api/v1/settings/tnc-additions/${tncId}`, data);
  return response.data;
}

/**
 * @purpose Deletes a global Terms & Conditions addition by its ID.
 * @param {string} tncId - The unique identifier of the TNC addition to delete.
 * @returns {Promise<void>} A promise that resolves when the TNC addition is successfully deleted.
 * @owner Gemini
 */
export async function deleteGlobalTnc(tncId: string): Promise<void> {
  await apiClient.delete<void>(`/api/v1/settings/tnc-additions/${tncId}`);
}
/**
 * @deprecated GET /api/v1/exports does not exist on the backend (returns 404).
 * Use listSheetExports(sheetId) or listScenarioExports(scenarioId) instead.
 * This function is kept only for backwards compatibility and will be removed.
 * @owner [Gemini]
 */
export async function listExportsHistory(): Promise<Array<{
  id: string; costing_sheet_id: string; scenario_id: string; user_id: string;
  revision_number: number; file_type: string; file_path: string; exported_at: string;
}>> {
  console.warn('[DEPRECATED] listExportsHistory() calls a non-existent endpoint. Use listSheetExports(sheetId) instead.');
  const response = await apiClient.get('/api/v1/exports');
  return response.data;
}
